apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-distancia
  labels:
    app: conversao-distancia
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: conversao-distancia
  template:
    metadata:
      labels:
        app: conversao-distancia
    spec:
      containers:
      - name: conversao-distancia
        image: conversao-distancia:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Serice
metadata:
  name: conversao-distancia
  spec: 
    selector:
      app: conversao-distancia
    ports:
    - protocol: TCP
      port: 80
      targetPort: 5000